/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_fabiosoaza_app_NativeCall */

#ifndef _Included_com_github_fabiosoaza_app_NativeCall
#define _Included_com_github_fabiosoaza_app_NativeCall
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_github_fabiosoaza_app_NativeCall_sayHello
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_github_fabiosoaza_app_NativeCall_sumIntegers
   (JNIEnv* env, jobject thisObject, jint first, jint second);

 JNIEXPORT void JNICALL Java_com_github_fabiosoaza_app_NativeCall_printMessage
    (JNIEnv* env, jobject thisObject, jstring message);

#ifdef __cplusplus
}
#endif
#endif
